micronaut:
  application:
    name: demo
  server:
    port: 9090
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
netty:
  default:
    allocator:
      max-order: 3
logger:
  levels:
    io.micronaut.transaction: TRACE
